### ISSUE TITLE
develop 브랜치 PR시, CI 빌드 테스트

### ISSUE THREAD

**Issue by yunabyte** [100-hours-a-week/4-bull4zo-cloud#78]
develop 브랜치 PR시, CI 빌드 테스트를 통해 코드 단 에러로 인한 develop 브랜치 워크플로우 실패를 사전에 방지
추후 BE, AI는 Docker 도입이 예정되어 있어, 일단 FE만 진행.

**Comment by yunabyte** [comment]
@gunhee0421 
FE 빌드 실패 후 워크플로우 동작 과정에 관한 논의가 필요합니다. 
```
  close-on-failure:
    if: failure()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Close PR on build failure
        uses: peter-evans/close-pull@v3
        with:
          comment: |
            로그 확인하기 (GitHub Actions)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            로컬에서 오류를 확인하고 다시 PR을 열어주세요.
```

1. 빌드 실패 → PR 자동 close 되는 거 괜찮으신가요? PR 자동 close 대신 로그만 출력하는 방안으로 변경 가능합니다.
2. 빌드 실패 시 comment에 에러 로그 출력과 '로컬에서 오류를 확인하고 다시 PR을 열어주세요.' 텍스트를 포함하는 워크플로우 추가하려고 합니다. 필요하신가요?

위 두 내용 살펴보시고 답변 부탁드립니다!
